export enum HttpStatus {
  OK = 200,
  BAD_REQUEST = 400,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
}

export enum ErrorCode {
  VALIDATION_FAILED = "VALIDATION_FAILED",
  UNKNOWN_MCP_SERVER = "UNKNOWN_MCP_SERVER",
  BLOCKED_TOOL = "BLOCKED_TOOL",
  UNKNOWN_PROVIDER = "UNKNOWN_PROVIDER",
  UNKNOWN_SKILL = "UNKNOWN_SKILL",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export enum OutputFormat {
  HTML = "html",
}
